import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import '@mantine/dates/styles.css';
import { MantineProvider, createTheme } from "@mantine/core";
import { Providers } from "./provider";
import { montserrat } from "../src/fonts/index";

export const metadata: Metadata = {
  title: "Patitas Felices",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const theme = createTheme({
  fontFamily: "var(--font-montserrat), sans-serif",
  headings: {
    fontFamily: "var(--font-montserrat), sans-serif",
  },
  breakpoints: {
    xs: "500px",
    sm: "768px",
    md: "992px",
    lg: "1280px",
    xl: "1920px",
  },
  primaryColor: "violet",
  primaryShade: 6,
  colors: {
    primary: [
      "#e6ffee",
      "#d3f9e0",
      "#a8f2c0",
      "#7aea9f",
      "#54e382",
      "#3bdf70",
      "#2bdd66",
      "#1bc455",
      "#0bae4a",
      "#00973c",
    ],
    secondary: [
      "#f3edff",
      "#e0d7fa",
      "#beabf0",
      "#9a7de6",
      "#7c55de",
      "#693cd9",
      "#5f30d8",
      "#4f23c0",
      "#461eac",
      "#3b1898",
    ],
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </Providers>
      </body>
    </html>
  );
}
